repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --strict-optional, --no-implicit-optional, --warn-unused-ignores, --disallow-untyped-defs]
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        language_version: python3.9
